import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import { SidebarDemo } from "@/components/Sidebar";
import 'leaflet/dist/leaflet.css'

import { Toaster } from '@/components/ui/toaster';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRM Web Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css"
        />
      </head>
      <body
        className={`${inter.className} antialiased h-screen`}>

        <AuthProvider>
          <div className="flex flex-row w-full h-full">
            
            {children}
            <Toaster/>
          </div>
        </AuthProvider>

      </body>
    </html>
  );
}
