import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import { SidebarDemo } from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased h-screen`}>

        <AuthProvider>
          <div className="flex flex-row w-full h-full">
            
            {children}
          </div>
        </AuthProvider>

      </body>
    </html>
  );
}
