import type { Metadata } from "next";

import { SidebarDemo } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "CRM Pro",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <div
        className={` antialiased h-screen w-full`}>

       
          <div className="flex flex-col w-full h-full sm:flex-row">
            <SidebarDemo />
            {children}
          </div>
       

     
    </div>
  );
}
